<?php
echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="utf-8" />
            <meta name="description" content="Goto Gro MRM" />
            <meta name="keywords" content="HTML5, CSS layout" />
            <meta name="author" content="Bugged"  />
            <title>Goto Gro MRM</title>
            <link href="../style/style.css" rel="stylesheet">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        </head>'
?>